# Generated by Django 3.2.10 on 2023-05-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bill_address', models.CharField(max_length=500)),
                ('ship_address', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('email2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('vat', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceapp.customers')),
            ],
        ),
    ]
